service: https://katie.mtech.edu/~tbrooks/AbOut/secret
casURL: https://mtlbsso.mtech.edu/idp/profile/cas/serviceValidate
jwtSecret: kYp3s6v9y$B&E)H@McQeThWmZq4t7w!z%C*F-JaNdRgUjXn2r5u8x/A?D(G+KbPe

server:
  #type: simple
  applicationContextPath: /
  applicationConnectors:
    - type: https
      port: 30120
      keyStorePath: /opt/lets/keystore.jks
      keyStorePassword: 
      validateCerts: false
      validatePeers: false
  adminConnectors:
    - type: http
      port: 8080
      bindHost: 127.0.0.1

logging:
  level: INFO
  loggers:
    edu.mtech.stout: DEBUG
  appenders:
    - type: file
      currentLogFilename: ./logs/stout.log
      #date and compress logs for previous days.
      archivedLogFilenamePattern: ./logs/stout-%d.log.gz
      archivedFileCount: 5
      timeZone: UTC

database:
  driverClass: com.mysql.jdbc.Driver 
  user: tbrooks
  password: 
  url: jdbc:mysql://localhost:3306/Stout
  maxWaitForConnection: 1s
  minSize: 4
  maxSize: 10
  evictionInterval: 10s
  checkConnectionWhileIdle: true
  checkConnectionOnReturn: true
  checkConnectionOnBorrow: true
              

